_BASE_: "meshed_memory.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'MSCoCoDataset'
  VAL: 'MSCoCoDataset'
  TEST: 'MSCoCoDataset'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 10 # one gpu
  SEQ_PER_SAMPLE: 1

######################################### Engine #########################################
ENGINE:
  NAME: 'RLBeamTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_xe_model}'

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 30
  BASE_LR: 0.000005
  BETAS: [0.9, 0.999]

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'

####################################### scorer ####################################### 
SCORER:
  NAME: 'PTBTokenizedScorer'
  GT_PATH: '../open_source_dataset/mscoco_dataset/coco_train_raw.pkl'
  CIDER_CACHED: ''