_BASE_: "base_att_image_caption.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 10
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/mscoco_dataset/features/up_down_36'
  ANNO_FOLDER:  '../open_source_dataset/mscoco_dataset'
  RELATION_FILE: '../open_source_dataset/mscoco_dataset/features/relation/relationship_coco.pkl'
  SEQ_PER_SAMPLE:  5
  MAX_FEAT_NUM: 36

######################################### MODEL #########################################
MODEL:
  ENCODER: 'GCNEncoder'
  #################################### Visual embedding ####################################
  VISUAL_EMBED:
    NAME: 'VisualIdentityEmbedding'
    IN_DIM: 2048
    OUT_DIM: 2048
  #################################### GCN ####################################
  GCN:
    IN_DIM: 2048
    OUT_DIM: 2048
    RELATION_NUM: 21
    DROPOUT: 0.5
  UPDOWN:
    ATT_EMBED_SIZE: 512
    DROPOUT1: 0.0
    DROPOUT2: 0.5
    ATT_EMBED_DROPOUT: 0.5

####################################### losses ####################################### 
LOSSES:
  NAMES: ['CrossEntropy']
